/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef TUGAS_BESAR_PRIVATE_H
#define TUGAS_BESAR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.1.0.0"
#define VER_MAJOR	2
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"2.1.0.0"
#define FILE_DESCRIPTION	"Tugas Besar Struktur Data"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Iqbal, Hendri, Nadia"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"SISTEM AKADEMIK INFORMATIKA"
#define PRODUCT_VERSION	"2.1.0.0"

#endif /*TUGAS_BESAR_PRIVATE_H*/
